services:
  go:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ~/.config/gcloud:/root/.config/gcloud
      - ~/.gitconfig:/root/.gitconfig
    env_file:
      - .env